apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-nginx-controller
rules:
  # Core resources the controller must observe cluster-wide
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods", "configmaps", "secrets", "namespaces", "nodes"]
    verbs: ["get", "list", "watch"]

  # EndpointSlices (modern clusters)
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]

  # Ingress objects + IngressClass
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "ingressclasses"]
    verbs: ["get", "list", "watch"]

  # Update ingress status (optional but common)
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses/status"]
    verbs: ["update"]

  # Events (to record sync / errors)
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]

  # Leader election (common)
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-nginx-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-nginx-controller
subjects:
  - kind: ServiceAccount
    name: ingress-nginx
    namespace: platform
